<a href="https://colab.research.google.com/github/hamednasr/neural-network-calculator/blob/main/my_code_neural_network_calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **neural network calculator**

In [37]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader,TensorDataset
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

# creat data sets

In [31]:
data = np.random.randint(-20,21,(3000,2))
data

array([[ -7, -13],
       [-19,   6],
       [-10,  -9],
       ...,
       [  2,   9],
       [ 19,  -2],
       [ -5,  10]])

In [32]:
labels = np.sum(data, axis =1)
labels

array([-20, -13, -19, ...,  11,  17,   5])

In [33]:
dataT = torch.tensor(data)
dataT

tensor([[ -7, -13],
        [-19,   6],
        [-10,  -9],
        ...,
        [  2,   9],
        [ 19,  -2],
        [ -5,  10]])

In [34]:
labelsT=torch.tensor(labels)
labelsT

tensor([-20, -13, -19,  ...,  11,  17,   5])

# crea dataloader objects

In [71]:
train_data,test_data,train_labels,test_labels = train_test_split(dataT,labelsT,test_size=0.1)

train_set = TensorDataset(train_data,train_labels)
test_set = TensorDataset(test_data,test_labels)

batchsize = 32
train_loader = DataLoader(train_set, batch_size=batchsize, shuffle=True, drop_last=True)
test_loader = DataLoader(test_set, batch_size=test_set.tensors[0].shape[0])

In [70]:
train_loader.dataset.tensors

(tensor([[-19,   0],
         [-12, -11],
         [ -3,   7],
         ...,
         [-16,   3],
         [-20, -20],
         [ -7,   8]]), tensor([-19, -23,   4,  ..., -13, -40,   1]))

In [74]:
def CreatModel():

  ANNcal = nn.Sequential(
              nn.Linear(2,128),
              nn.ReLU(),
              nn.Linear(128,256),
              nn.ReLU(),
              nn.Linear(256,256),
              nn.ReLU(),
              nn.Linear(256,41) 
                        )

  lossfun = nn.CrossEntropyLoss()

  optimizer = torch.optim.Adam(params=ANNcal.parameters(), lr=0.005)

  return ANNcal, lossfun, optimizer