<a href="https://colab.research.google.com/github/hamednasr/neural-network-calculator/blob/main/my_code_neural_network_calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt

In [31]:
data = np.random.randint(-20,21,(3000,2))
data

array([[ -7, -13],
       [-19,   6],
       [-10,  -9],
       ...,
       [  2,   9],
       [ 19,  -2],
       [ -5,  10]])

In [32]:
labels = np.sum(data, axis =1)
labels

array([-20, -13, -19, ...,  11,  17,   5])

In [33]:
dataT = torch.tensor(data)
dataT

tensor([[ -7, -13],
        [-19,   6],
        [-10,  -9],
        ...,
        [  2,   9],
        [ 19,  -2],
        [ -5,  10]])

In [34]:
labelsT=torch.tensor(labels)
labelsT

tensor([-20, -13, -19,  ...,  11,  17,   5])