<a href="https://colab.research.google.com/github/hamednasr/neural-network-calculator/blob/main/my_code_neural_network_calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **neural network calculator**

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader,TensorDataset
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

# creat data sets

In [42]:
data = np.random.randint(-20,21,(3000,2))
data

array([[-16,  20],
       [ 11,  -5],
       [ -4,   4],
       ...,
       [-19,  20],
       [  8,   0],
       [ 20,   5]])

In [43]:
z = np.sum(data, axis =1)
z = z[:,None]
z

array([[ 4],
       [ 6],
       [ 0],
       ...,
       [ 1],
       [ 8],
       [25]])

In [44]:
dataT = torch.FloatTensor(data)
dataT

tensor([[-16.,  20.],
        [ 11.,  -5.],
        [ -4.,   4.],
        ...,
        [-19.,  20.],
        [  8.,   0.],
        [ 20.,   5.]])

In [45]:
zT=torch.FloatTensor(z)
zT

tensor([[ 4.],
        [ 6.],
        [ 0.],
        ...,
        [ 1.],
        [ 8.],
        [25.]])

# create dataloader objects

In [46]:
train_data,test_data,train_labels,test_labels = train_test_split(dataT,zT,test_size=0.1)

train_sets = TensorDataset(train_data,train_labels)
test_sets = TensorDataset(test_data,test_labels)

batchsize = 32
train_loader = DataLoader(train_sets, batch_size=batchsize, shuffle=True, drop_last=True)
test_loader = DataLoader(test_sets, batch_size=test_sets.tensors[0].shape[0])

In [47]:
train_loader.dataset.tensors

(tensor([[-14.,  -5.],
         [ 10.,  16.],
         [-10.,  14.],
         ...,
         [  8.,   8.],
         [-20.,  10.],
         [  8.,  -3.]]), tensor([[-19.],
         [ 26.],
         [  4.],
         ...,
         [ 16.],
         [-10.],
         [  5.]]))

# creat model

In [21]:
def CreatModel():

  ANNcal = nn.Sequential(
              nn.Linear(2,128),
              nn.ReLU(),
              nn.Linear(128,256),
              nn.ReLU(),
              nn.Linear(256,256),
              nn.ReLU(),
              nn.Linear(256,1) 
                        )

  lossfun = nn.MSELoss()

  optimizer = torch.optim.Adam(params=ANNcal.parameters(), lr=0.005)

  return ANNcal, lossfun, optimizer

## test the created model:

In [31]:
ANNcal, lossfun, optimizer = CreatModel()
d = torch.FloatTensor(np.random.randint(-20,21,(3,2)))

l = torch.sum(d,axis=1)
l = l[:,None]
# print(d)
print('data is: \n', d)
print('label is: \n', l)
print(l.shape)
yhat = ANNcal(d)
print(yhat)
print(nn.MSELoss()(yhat,l))#.detach().item()
# print('yhat is: \n', yhat)
np.corrcoef(l.T,yhat.detach().T)[0,1]

data is: 
 tensor([[-15.,  17.],
        [-10., -14.],
        [-13.,   1.]])
label is: 
 tensor([[  2.],
        [-24.],
        [-12.]])
torch.Size([3, 1])
tensor([[0.3826],
        [0.6379],
        [0.3799]], grad_fn=<AddmmBackward0>)
tensor(254.3016, grad_fn=<MseLossBackward0>)


-0.8381093194612155